project_id          = "your-gcp-project-id"
region              = "us-central1"
bucket_name         = "your-gcp-project-id-meet-audio-temp"
artifact_repo_name  = "enterprise-meet-notes-repo"
tasks_queue_name    = "meet-notes-queue"
bigquery_dataset_id = "enterprise_portal_analytics"
service_account_id  = "enterprise-meet-notes-sa"
